### ISSUE TITLE
Use of StatefulSets for persistent apps

### ISSUE THREAD

**Issue by jusabatier** [georchestra/helm-georchestra#122]
I continue to discover the K8S stack, and try to deploy a Georchestra stack in it is a good practice.

In the chart README, it's explained that we must use "Recreate" as update strategy for deployment.

I I understand this post : https://spacelift.io/blog/statefulset-vs-deployment

the best way to handle stateful apps (persistence) is to use "StatefulSets".

Is there a reason to use Deployment for them in this chart ?

**Comment by edevosc2c** [comment]
Good question.

Well first, I would like to point out that this helm chart has only been tested on a single Kubernetes node. This is why Deployments will somewhat act like a Statefulset since all the apps are running on one node.

A statefulset has its flaws. The first one being that Rolling release deployment strategy do not exist. Recently, we migrated geoserver from Recreate strategy to Rolling since we concluded that it didn't harm anything.

The second big one is that PVC created through the Statefulset are bound to a specific node. At Camptocamp we have Kubernetes clusters that get their nodes updated by replacing with a new one.

And finally, all the limitations listed here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations. Some may be a real burner if you get into these situations.
