### ISSUE TITLE
Allow configuring nodeSelector

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/helm-georchestra#43]
It would be nice to have the possibility to set additional nodeSelector filters. At least a global one common to the georchestra stack

**Comment by edevosc2c** [comment]
Only a global one would be a candidate because georchestra is not yet tested for having some of its components distributed across multiple nodes. Some components may work on different nodes (any component not having a hard requirement on shared PVC) though.

Currently, the alternative is to force pods in a namespace to be assigned to a specific node like this: https://stackoverflow.com/a/52487334   
That's how it is done at camptocamp.

**Comment by jeanpommier** [comment]
> georchestra is not yet tested for having some of its components distributed across multiple nodes

in that case, I believe it is really necessary to handle at least the nodeSelector if not the affinity section.

Thanks for the PodNodeSelector hint, I didn't know about it. It can be an alternative, but it seems to me that it lacks flexibility. One might want to host in the same namespace other services that don't have this requirement.

**Comment by jeanpommier** [comment]
> any component not having a hard requirement on a shared PVC

You're thinking mostly of the case where you're using localPath volumes, right ?

If you use distributed storage, I don't see what would prevent one from spreading the containers across several nodes

**Comment by edevosc2c** [comment]
> > any component not having a hard requirement on a shared PVC
> 
> You're thinking mostly of the case where you're using localPath volumes, right ?
> 
> If you use distributed storage, I don't see what would prevent one from spreading the containers across several nodes

Yes when using a local storage.

From my experience distributed storage doesn't work great, it's slow, always buggy and hard to maintain. When possible, it's always better to put the replication in the logic side of the application (for instance PostgreSQL).
